### ISSUE TITLE
I get an error message

### ISSUE THREAD

**Issue by BLUBBSON** [Shawesome4u/Shawesomes_Divine_Armaments#1]
Hey quick note, I get the following error when starting Valheim

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
EffectArea.Awake () (at <79989041713a40fba2973f1624473248>:0)
UnityEngine.Object:Instantiate(Transform)
shawcape.Shawesomes_Divine_Armaments:CopyIntoParent(Transform, Transform)
shawcape.Shawesomes_Divine_Armaments:Addjmcgoddess()
shawcape.Shawesomes_Divine_Armaments:Additems()
Jotunn.EventExtensions:SafeInvoke(Action) (at D:/Projects/Jotunn/JotunnLib/Extensions/EventExtensions.cs:26)
Jotunn.Managers.PrefabManager:InvokeOnVanillaObjectsAvailable() (at D:/Projects/Jotunn/JotunnLib/Managers/PrefabManager.cs:410)
Jotunn.Managers.Patches:InvokeOnVanillaObjectsAvailable(ObjectDB) (at D:/Projects/Jotunn/JotunnLib/Managers/PrefabManager.cs:92)
ObjectDB:DMD<ObjectDB::CopyOtherDB>(ObjectDB, ObjectDB)
FejdStartup:DMD<FejdStartup::SetupObjectDB>(FejdStartup)
FejdStartup:DMD<FejdStartup::Start>(FejdStartup)

**Comment by Shawesome4u** [comment]
i have been scratching my head at what exact its saying is missing im trying to fix it by tonight! Thank you!

**Comment by Shawesome4u** [comment]
and suuuuper sorry for late reply i didnt think anyone used the github comments lol

**Comment by Shawesome4u** [comment]
This has been fixed XD thanks again!
